language: java
# os: [osx, linux]
env:
  global:
    # This is a convenience variable for shortening download commands
    - GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"
  matrix:
  - JDK="adopt@1.12"
  - JDK="adopt-openj9@1.12"
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
services:
- mysql
before_cache:
  - curl "${GRAVIS}.clean_gradle_cache.sh" --output ~/.clean_gradle_cache.sh
  - bash ~/.clean_gradle_cache.sh
before_install:
  - cp COOL/src/main/resources/config_example.yml COOL/src/main/resources/config.yml
  - mysql -u root < COOL/resources/foodmart.sql
  - mysql -e 'use foodmart; select * from `customer` limit 5;'
  - mysql -u root < COOL/resources/meta-foodmart.sql
  - mysql -e 'use meta-foodmart; select * from `fact` limit 5;'
script:
  - cd COOL
  - chmod +x gradlew
  - ./gradlew