name: "build"
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./COOL
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - uses: actions/setup-java@v4.2.1
        with:
          distribution: 'adopt'
          java-version: '14'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Init
        run: |
          chmod +x *.sh
          ./init.sh
          cd src/main/python
          source venv/bin/acrivate
          python -m unittest discover
      - name: Test Kotlin
        run: |
          ./download.sh
          ./start.sh
          ./gradlew --stacktrace --scan
          ./stop.sh
      - name: Generate the charts
        run: |
          cd src/main/python
          pip install jupyter
          jupyter nbconvert --execute --to notebook --inplace charts.ipynb

  release:
    defaults:
      run:
        working-directory: ./COOL
    needs:
      - build
    if: github.event_name == 'push'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-java@v4.2.1
        with:
          distribution: 'adopt'
          java-version: '14'
      - name: Deploy
        run: |
          chmod +x ./gradlew  
          ./gradlew shadowJar
      - name: Release
        run: |
          npm install
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
