name: "build"

on:
  push:
    tags: '*'
    branches: '**'
    # branches-ignore:
    #   - 'autodelivery**'
    #   - 'bump-**'
    #   - 'renovate/**'
    paths-ignore:
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'README.md'
      - 'renovate.json'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '14' ]
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-java@v2.5.0
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10.2'
          architecture: 'x64'
      - name: Init
        run: |
          cd COOL
          chmod +x *.sh
          ./init.sh
      - name: Test python
        run: |
          cd COOL/src/main/python
          pip install -r requirements.txt
          pip freeze
          python -m unittest discover
      - name: Test Kotlin
        run: |
          cd COOL
          ./build.sh
          ./download.sh
          ./start.sh
          ./gradlew --stacktrace
          ./stop.sh

  release:
    needs:
      - build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - uses: actions/setup-java@v2.5.0
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: Deploy
        run: |
          cd COOL
          chmod +x ./gradlew
          ./gradlew shadowJar
          cd ..
          mkdir -p dist/
          cp COOL/build/libs/* dist/
      - name: Release
        run: |
          npm install
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}