name: "build"
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '14' ]
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: actions/setup-java@v3.1.1
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: Run docker
        run: |
          cd COOL
          cp .env.example .env
          cp src/main/resources/config.example.yml src/main/resources/config.yml
          chmod +x *.sh
          ./build.sh
          ./download.sh
          ./start.sh
      - name: Build
        run: |
          cd COOL
          chmod +x ./gradlew
          ./gradlew
      - name: Stop docker
        run: |
          cd COOL
          ./stop.sh
