name: "build"

on:
  push:
    tags: '*'
    branches-ignore:
      - 'autodelivery**'
      - 'bump-**'
      - 'renovate/**'
    paths-ignore:
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'README.md'
      - 'renovate.json'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '14' ]
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-java@v2.5.0
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: Run docker
        run: |
          cd COOL
          chmod +x *.sh
          ./init.sh
          ./build.sh
          ./download.sh
          ./start.sh
          ./gradlew
          ./stop.sh

  release:
    needs:
      - build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Deploy
        run: |
          cd COOL
          chmod +x ./gradlew
          ./gradlew shadowJar
          cd ..
          mkdir -p dist/
          cp COOL/build/libs/* dist/
      - name: Release
        run: |
          npm install
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}