name: "build"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./COOL
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-java@v2.5.0
        with:
          distribution: 'adopt'
          java-version: '14'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10.2'
          architecture: 'x64'
      - name: Init
        run: |
          chmod +x *.sh
          ./init.sh
      - name: Install and test python
        run: |
          cd src/main/python
          pip install -r requirements.txt
          python -m unittest discover
      - name: Test Kotlin
        run: |
          ./build.sh
          ./download.sh
          ./start.sh
          ./gradlew --stacktrace --scan
          ./stop.sh
      - name: Generate the charts
        run: |
          cd src/main/python
          pip install jupyter
          jupyter nbconvert --execute --to notebook --inplace charts.ipynb

  release:
    defaults:
      run:
        working-directory: ./COOL
    needs:
      - build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - uses: actions/setup-java@v2.5.0
        with:
          distribution: 'adopt'
          java-version: '14'
      - name: Deploy
        run: |
          chmod +x ./gradlew  
          ./gradlew shadowJar
          cd ..
          mkdir -p dist/
          cp build/libs/* dist/
      - name: Release
        run: |
          npm install
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}