python: "C:/Users/matteo.francia5/Documents/repos/experiments-assess/intentional/src/main/python/"
webapp: sales_fact_1997
cubes:
#  - dataMart: research
#    factTable: lineorder100
#    synonyms:
#      - SSBORA100
#    metadata: research
#    dbms: oracle
#    ip: 137.204.74.10
#    port: 1521
#    create: true
#    importmembers: false
#    user: ssb100
#    pwd: ssb100
#  - dataMart: research
#    factTable: lineorder10
#    synonyms:
#      - SSBORA10
#    metadata: research
#    dbms: oracle
#    ip: 137.204.74.10
#    port: 1521
#    create: true
#    importmembers: true
#    user: ssb10
#    pwd: ssb10
#  - dataMart: research
#    factTable: lineorder2
#    synonyms:
#      - SSBORA
#    metadata: research
#    dbms: oracle
#    ip: 137.204.74.10
#    port: 1521
#    create: false
#    importmembers: true
#    user: ssb_flight
#    pwd: ssb_flight
  - dataMart: research
    factTable: sales_fact_1997
    synonyms:
      - SALES
    metadata: research
    dbms: oracle
    ip: 137.204.74.10
    port: 1521
    create: false
    importmembers: true
    user: foodmart
    pwd: foodmart